const jokes = [
  {
    type: "general",
    setup: "What do birds give out on Halloween?",
    punchline: "Tweets.",
    id: 187,
  },
  {
    type: "programming",
    setup: "Why do programmers prefer dark chocolate?",
    punchline: "Because it's bitter like their code.",
    id: 416,
  },
  {
    type: "general",
    setup: "Do you know where you can get chicken broth in bulk?",
    punchline: "The stock market.",
    id: 106,
  },
  {
    type: "general",
    setup:
      "When a dad drives past a graveyard: Did you know that's a popular cemetery?",
    punchline: "Yep, people are just dying to get in there",
    id: 50,
  },
  {
    type: "general",
    setup: "Why did the tree go to the dentist?",
    punchline: "It needed a root canal.",
    id: 335,
  },
  {
    type: "general",
    setup: "How do you organize a space party?",
    punchline: "You planet.",
    id: 129,
  },
  {
    type: "programming",
    setup: "How many React developers does it take to change a lightbulb?",
    punchline: "None, they prefer dark mode.",
    id: 410,
  },
  {
    type: "general",
    setup: "Why are ghosts bad liars?",
    punchline: "Because you can see right through them!",
    id: 300,
  },
  {
    type: "general",
    setup: "Why did the cookie go to the doctor?",
    punchline: " Because it was feeling crumbly.",
    id: 434,
  },
  {
    type: "general",
    setup: "Where was the Declaration of Independence signed?",
    punchline: "At the bottom! ",
    id: 293,
  },
  {
    type: "general",
    setup: "Why didn't the number 4 get into the nightclub?",
    punchline: "Because he is 2 square.",
    id: 337,
  },
  {
    type: "general",
    setup: "What is the least spoken language in the world?",
    punchline: "Sign Language",
    id: 247,
  },
  {
    type: "knock-knock",
    setup:
      "Knock knock. \n Who's there? \n A broken pencil. \n A broken pencil who?",
    punchline: "Never mind. It's pointless.",
    id: 11,
  },
  {
    type: "general",
    setup:
      "I got hit in the head by a soda can, but it didn't hurt that much...",
    punchline: "It was a soft drink.",
    id: 68,
  },
  {
    type: "general",
    setup: "What's brown and sticky?",
    punchline: "A stick.",
    id: 266,
  },
  {
    type: "general",
    setup: "Why couldn't the bicycle stand up by itself?",
    punchline: "It was two-tired.",
    id: 421,
  },
  {
    type: "general",
    setup: "What is a centipedes's favorite Beatle song?",
    punchline: "I want to hold your hand, hand, hand, hand...",
    id: 239,
  },
  {
    type: "general",
    setup: "Why does Superman get invited to dinners?",
    punchline: "Because he is a Supperhero.",
    id: 360,
  },
  {
    type: "general",
    setup: "A grocery store cashier asked if I would like my milk in a bag.",
    punchline: "I told her 'No, thanks. The carton works fine.'",
    id: 397,
  },
  {
    type: "general",
    setup: "What is a witch's favorite subject in school?",
    punchline: "Spelling!",
    id: 242,
  },
  {
    type: "general",
    setup: "What did the shy pebble wish for?",
    punchline: "That she was a little boulder.",
    id: 184,
  },
  {
    type: "general",
    setup: "If you boil a clown...",
    punchline: "Do you get a laughing stock?",
    id: 44,
  },
  {
    type: "general",
    setup: "Why do pirates not know the alphabet?",
    punchline: 'They always get stuck at "C".',
    id: 349,
  },
  {
    type: "general",
    setup: "Can February march?",
    punchline: "No, but April may.",
    id: 81,
  },
  {
    type: "general",
    setup: "Why does Norway have barcodes on their battleships?",
    punchline: "So when they get back to port, they can Scandinavian.",
    id: 359,
  },
  {
    type: "general",
    setup: "Why are fish so smart?",
    punchline: "Because they live in schools!",
    id: 299,
  },
  {
    type: "programming",
    setup: "Why did the functions stop calling each other?",
    punchline: "Because they had constant arguments.",
    id: 406,
  },
  {
    type: "programming",
    setup:
      "A programmer puts two glasses on his bedside table before going to sleep.",
    punchline:
      "A full one, in case he gets thirsty, and an empty one, in case he doesn’t.",
    id: 364,
  },
  {
    type: "general",
    setup: "When do doctors get angry?",
    punchline: "When they run out of patients.",
    id: 280,
  },
  {
    type: "general",
    setup: "Why did the invisible man turn down the job offer?",
    punchline: "He couldn't see himself doing it",
    id: 51,
  },
  {
    type: "general",
    setup: "If you see a robbery at an Apple Store...",
    punchline: "Does that make you an iWitness?",
    id: 41,
  },
  {
    type: "programming",
    setup: "What is the most used language in programming?",
    punchline: "Profanity.",
    id: 381,
  },
  {
    type: "general",
    setup: "What happens when you anger a brain surgeon?",
    punchline: "They will give you a piece of your mind.",
    id: 237,
  },
  {
    type: "general",
    setup: "How do you find Will Smith in the snow?",
    punchline: "Look for fresh prints.",
    id: 121,
  },
  {
    type: "general",
    setup: "What do you call a bee that can't make up its mind?",
    punchline: "A maybe.",
    id: 372,
  },
  {
    type: "general",
    setup: "What do you do when you see a space man?",
    punchline: "Park your car, man.",
    id: 227,
  },
  {
    type: "general",
    setup: "Did you hear the story about the cheese that saved the world?",
    punchline: "It was legend dairy.",
    id: 65,
  },
  {
    type: "general",
    setup: "Why did the tomato blush?",
    punchline: "Because it saw the salad dressing.",
    id: 334,
  },
  {
    type: "general",
    setup: "What did the digital clock say to the grandfather clock?",
    punchline: "Look, no hands!",
    id: 169,
  },
  {
    type: "general",
    setup: "Why did the cookie cry?",
    punchline: "Because his mother was a wafer so long",
    id: 320,
  },
  {
    type: "general",
    setup: "How does a penguin build it’s house?",
    punchline: "Igloos it together.",
    id: 134,
  },
  {
    type: "general",
    setup: "What do you get hanging from Apple trees?",
    punchline: "Sore arms.",
    id: 228,
  },
  {
    type: "general",
    setup: "What did the dog say to the two trees?",
    punchline: "Bark bark.",
    id: 170,
  },
  {
    type: "general",
    setup: "Did you hear the one about the guy with the broken hearing aid?",
    punchline: "Neither did he.",
    id: 100,
  },
  {
    type: "general",
    setup:
      "What did Romans use to cut pizza before the rolling cutter was invented?",
    punchline: "Lil Caesars",
    id: 164,
  },
  {
    type: "general",
    setup: "Why don't oysters give to charity?",
    punchline: "Because they're shellfish.",
    id: 432,
  },
  {
    type: "general",
    setup: "What is a tornado's favorite game to play?",
    punchline: "Twister!",
    id: 240,
  },
  {
    type: "general",
    setup: "What do you call a pig with three eyes?",
    punchline: "Piiig",
    id: 213,
  },
  {
    type: "general",
    setup: "What musical instrument is found in the bathroom?",
    punchline: "A tuba toothpaste.",
    id: 259,
  },
  {
    type: "programming",
    setup: "What’s the object-oriented way to become wealthy?",
    punchline: "Inheritance.",
    id: 371,
  },
  {
    type: "general",
    setup: "Why are pirates called pirates?",
    punchline: "Because they arrr!",
    id: 304,
  },
  {
    type: "general",
    setup: "What did the traffic light say to the car as it passed?",
    punchline: "Don't look I'm changing!",
    id: 185,
  },
  {
    type: "programming",
    setup: "I was gonna tell you a joke about UDP...",
    punchline: "...but you might not get it.",
    id: 71,
  },
  {
    type: "general",
    setup: "Where did you learn to make ice cream?",
    punchline: "Sunday school.",
    id: 283,
  },
  {
    type: "general",
    setup: "I just watched a documentary about beavers.",
    punchline: "It was the best dam show I ever saw",
    id: 40,
  },
  {
    type: "general",
    setup: "What's orange and sounds like a parrot?",
    punchline: "A Carrot.",
    id: 267,
  },
  {
    type: "general",
    setup: "What do you call a careful wolf?",
    punchline: "Aware wolf.",
    id: 194,
  },
  {
    type: "general",
    setup:
      "How do you tell the difference between a crocodile and an alligator?",
    punchline: "You will see one later and one in a while.",
    id: 131,
  },
  {
    type: "programming",
    setup: "Why did the private classes break up?",
    punchline: "Because they never saw each other.",
    id: 407,
  },
  {
    type: "general",
    setup:
      "Did you hear about the scientist who was lab partners with a pot of boiling water?",
    punchline: "He had a very esteemed colleague.",
    id: 94,
  },
  {
    type: "general",
    setup: "What kind of magic do cows believe in?",
    punchline: "MOODOO.",
    id: 254,
  },
  {
    type: "general",
    setup: "What do you get when you cross a chicken with a skunk?",
    punchline: "A fowl smell!",
    id: 230,
  },
  {
    type: "general",
    setup: "Why are skeletons so calm?",
    punchline: "Because nothing gets under their skin.",
    id: 305,
  },
  {
    type: "general",
    setup: "How does a dyslexic poet write?",
    punchline: "Inverse.",
    id: 132,
  },
  {
    type: "programming",
    setup: "Why did the programmer bring a ladder to work?",
    punchline: "They heard the code needed to be debugged from a higher level.",
    id: 441,
  },
  {
    type: "programming",
    setup: "How do you check if a webpage is HTML5?",
    punchline: "Try it out on Internet Explorer",
    id: 55,
  },
  {
    type: "programming",
    setup: "Why would a guitarist become a good programmer?",
    punchline: "He's adept at riffing in C#.",
    id: 14,
  },
  {
    type: "general",
    setup: "What do elves post on Social Media?",
    punchline: "Elf-ies.",
    id: 401,
  },
  {
    type: "general",
    setup: "What do you call a fat psychic?",
    punchline: "A four-chin teller.",
    id: 205,
  },
  {
    type: "general",
    setup: "Why can’t you hear a pterodactyl go to the bathroom?",
    punchline: "The p is silent.",
    id: 309,
  },
  {
    type: "general",
    setup: "Why do wizards clean their teeth three times a day?",
    punchline: "To prevent bat breath!",
    id: 354,
  },
  {
    type: "general",
    setup: "How come a man driving a train got struck by lightning?",
    punchline: "He was a good conductor.",
    id: 114,
  },
  {
    type: "general",
    setup: "Bad at golf?",
    punchline: "Join the club.",
    id: 79,
  },
  {
    type: "general",
    setup: "Why did the coffee file a police report?",
    punchline: "It got mugged.",
    id: 431,
  },
  {
    type: "programming",
    setup: "What do you call a computer mouse that swears a lot?",
    punchline: "A cursor!",
    id: 435,
  },
  {
    type: "general",
    setup:
      "My older brother always tore the last pages of my comic books, and never told me why.",
    punchline: "I had to draw my own conclusions.",
    id: 386,
  },
  {
    type: "general",
    setup: "Why do bears have hairy coats?",
    punchline: "Fur protection.",
    id: 341,
  },
  {
    type: "general",
    setup: "Why did the golfer wear two pairs of pants?",
    punchline: "In case he got a hole in one.",
    id: 433,
  },
  {
    type: "general",
    setup: "What did one nut say as he chased another nut?",
    punchline: "I'm a cashew!",
    id: 160,
  },
  {
    type: "general",
    setup: "What did celery say when he broke up with his girlfriend?",
    punchline: "She wasn't right for me, so I really don't carrot all.",
    id: 158,
  },
  {
    type: "general",
    setup: "What did the ocean say to the shore?",
    punchline: "Nothing, it just waved.",
    id: 179,
  },
  {
    type: "general",
    setup: "What do you call corn that joins the army?",
    punchline: "Kernel.",
    id: 223,
  },
  {
    type: "general",
    setup: "Why did the cowboy have a weiner dog?",
    punchline: "Somebody told him to get a long little doggy.",
    id: 322,
  },
  {
    type: "general",
    setup: "What's the difference between a hippo and a zippo?",
    punchline: "One is really heavy, the other is a little lighter.",
    id: 271,
  },
  {
    type: "general",
    setup: "Why did the barber win the race?",
    punchline: "He took a short cut.",
    id: 315,
  },
  {
    type: "general",
    setup: "Want to hear a joke about a piece of paper?",
    punchline: "Never mind...it's tearable",
    id: 39,
  },
  {
    type: "general",
    setup: "Did you hear about the crime in the parking garage?",
    punchline: "It was wrong on so many levels.",
    id: 394,
  },
  {
    type: "general",
    setup: "What cheese can never be yours?",
    punchline: "Nacho cheese.",
    id: 156,
  },
  {
    type: "programming",
    setup: "Why don't programmers like nature?",
    punchline: "There's too many bugs.",
    id: 419,
  },
  {
    type: "general",
    setup: "What do you call sad coffee?",
    punchline: "Despresso.",
    id: 61,
  },
  {
    type: "programming",
    setup: "The punchline often arrives before the set-up.",
    punchline: "Do you know the problem with UDP jokes?",
    id: 72,
  },
  {
    type: "general",
    setup: "What did the late tomato say to the early tomato?",
    punchline: "I’ll ketch up",
    id: 175,
  },
  {
    type: "general",
    setup: "Who did the wizard marry?",
    punchline: "His ghoul-friend",
    id: 296,
  },
  {
    type: "general",
    setup: "Did you hear about the two silk worms in a race?",
    punchline: "It ended in a tie.",
    id: 19,
  },
  {
    type: "general",
    setup: "Ever wondered why bees hum?",
    punchline: "It's because they don't know the words.",
    id: 108,
  },
  {
    type: "general",
    setup:
      "Due to complaints, Hawaii passed a law where you're not allowed to laugh above a certain decibel.",
    punchline: "You can only use a low ha.",
    id: 403,
  },
  {
    type: "general",
    setup: "Well...",
    punchline: "That’s a deep subject.",
    id: 64,
  },
  {
    type: "general",
    setup: "What do you call a thieving alligator?",
    punchline: "A crookodile!",
    id: 451,
  },
  {
    type: "general",
    setup: "Did you hear about the new restaurant on the moon?",
    punchline: "The food is great, but there’s just no atmosphere.",
    id: 92,
  },
  {
    type: "general",
    setup: "Why did the scarecrow win an award?",
    punchline: "Because he was outstanding in his field.",
    id: 430,
  },
];
